import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SyncGithubUser from "@/components/auth/SyncGithubUser";
import { SessionProvider } from "next-auth/react";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <SessionProvider>
      <html
        lang="en"
        className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        suppressHydrationWarning
      >
        <body className="min-h-full flex flex-col"><SyncGithubUser />
        <Navbar/>
        {children}
        </body>
      </html>
    </SessionProvider>
    
  );
}
